session:
  name: session_id
  secret_key: abc123
db:
  default:
    drivename: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: 131400
    dbname: shpuser
redis:
  default:
    addr:
    password:
    db: 12
oauth2:
  client:
    - id: test_client_1
      secret: test_secret_1
      name: 测试应用1
      domain: http://localhost:9093
      scope:
        - id: all
          title: 用户账号, 手机, 权限, 角色等信息

    - id: test_client_2
      secret: test_secret_2
      name: 测试应用2
      domain: http://localhost:9094
      scope:
        - id: all
          title: 用户账号, 手机, 权限, 角色等信息